version: '3.3'
services:
    fastapi_server:
        build: .
        command: fastapi run /usr/app/fastapi_server.py
        volumes:
            - ./fastapi_server.py:/usr/app/app/fastapi_server.py:ro
            - ./ocr/:/usr/app/ocr
        expose:
            - 8000
        ports:
                - "0.0.0.0:8000:8000/tcp"
        networks: 
                - ollama_network

    ollama:
        image: ollama/ollama:latest
        container_name: ollama
        networks:
            - ollama_network
        volumes:
            - ollama_data:/root/.ollama
        expose:
            - 11434
        ports:
            - "11434:11434"
        restart: unless-stopped

networks:
    ollama_network:
        driver: bridge
volumes:
    ollama_data:
        name: ollama_data
